import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../models/air_quality_alert.dart';
import '../utils/aqi_threshold_helper.dart';

class AlertService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;

  String? get _userId => _auth.currentUser?.uid;

  /// Stream of alerts for the current user, ordered by creation date descending
  Stream<List<AirQualityAlert>> getAlertsStream() {
    final userId = _userId;
    if (userId == null) return Stream.value([]);

    return _firestore
        .collection('users')
        .doc(userId)
        .collection('alerts')
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) => AirQualityAlert.fromFirestore(doc))
          .toList();
    });
  }

  /// Evaluates AQI data and generates an alert if it exceeds the user's threshold
  Future<void> checkAndGenerateAlert(String location, int aqi) async {
    final userId = _userId;
    if (userId == null) return;

    final prefs = await getPreferences();
    final bool enabled = prefs?['enabled'] ?? true;
    final int threshold = prefs?['threshold'] ?? 100;

    if (enabled && aqi >= threshold) {
      final category = AQIThresholdHelper.getCategory(aqi);
      final categoryName = AQIThresholdHelper.getCategoryName(category);
      
      final alert = AirQualityAlert(
        id: '', // Generated by Firestore
        userId: userId,
        aqi: aqi,
        category: categoryName,
        message: 'High AQI detected in $location: $aqi ($categoryName)',
        location: location,
        createdAt: DateTime.now(),
        type: AlertType.alert,
      );

      await saveAlert(alert);
    }
  }

  /// Saves an alert if it's not a duplicate within the last hour
  Future<void> saveAlert(AirQualityAlert alert) async {
    final userId = _userId;
    if (userId == null) return;

    try {
      final oneHourAgo = DateTime.now().subtract(const Duration(hours: 1));
      
      final duplicateQuery = await _firestore
          .collection('users')
          .doc(userId)
          .collection('alerts')
          .where('location', isEqualTo: alert.location)
          .where('message', isEqualTo: alert.message)
          .where('createdAt', isGreaterThan: Timestamp.fromDate(oneHourAgo))
          .limit(1)
          .get();

      if (duplicateQuery.docs.isEmpty) {
        await _firestore
            .collection('users')
            .doc(userId)
            .collection('alerts')
            .add(alert.toMap());
      }
    } catch (e) {
      rethrow;
    }
  }

  Future<void> markAsRead(String alertId) async {
    final userId = _userId;
    if (userId == null) return;
    await _firestore
        .collection('users')
        .doc(userId)
        .collection('alerts')
        .doc(alertId)
        .update({'isRead': true});
  }

  Future<void> deleteAlert(String alertId) async {
    final userId = _userId;
    if (userId == null) return;
    await _firestore
        .collection('users')
        .doc(userId)
        .collection('alerts')
        .doc(alertId)
        .delete();
  }

  Stream<int> getUnreadCount() {
    final userId = _userId;
    if (userId == null) return Stream.value(0);
    return _firestore
        .collection('users')
        .doc(userId)
        .collection('alerts')
        .where('isRead', isEqualTo: false)
        .snapshots()
        .map((snapshot) => snapshot.docs.length);
  }

  Future<void> savePreferences({
    required bool enabled,
    required int threshold,
    required bool sensitiveGroupAlerts,
  }) async {
    final userId = _userId;
    if (userId == null) return;
    await _firestore.collection('users').doc(userId).set({
      'notificationPreferences': {
        'enabled': enabled,
        'threshold': threshold,
        'sensitiveGroupAlerts': sensitiveGroupAlerts,
      }
    }, SetOptions(merge: true));
  }

  Future<Map<String, dynamic>?> getPreferences() async {
    final userId = _userId;
    if (userId == null) return null;
    final doc = await _firestore.collection('users').doc(userId).get();
    final data = doc.data();
    return data?['notificationPreferences'] as Map<String, dynamic>?;
  }
}
