// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBf40h-KiRk2uyfwpMZx3hwT0z_n8rm-E',
    appId: '1:871067145800:web:01d63b7c005dac5849ea7d',
    messagingSenderId: '871067145800',
    projectId: 'air-quality-8d73c',
    authDomain: 'air-quality-8d73c.firebaseapp.com',
    storageBucket: 'air-quality-8d73c.firebasestorage.app',
    measurementId: 'G-WHBK3TJXZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7L3_INF3JNS5B8GVEVEMrtDC6T0LagvE',
    appId: '1:871067145800:android:02bcc617bbe8125549ea7d',
    messagingSenderId: '871067145800',
    projectId: 'air-quality-8d73c',
    storageBucket: 'air-quality-8d73c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgj0J4JuP1WbQQfk2N8RWjhvNgXRNQTMQ',
    appId: '1:871067145800:ios:148250e92bfac3e349ea7d',
    messagingSenderId: '871067145800',
    projectId: 'air-quality-8d73c',
    storageBucket: 'air-quality-8d73c.firebasestorage.app',
    iosClientId: '871067145800-g0rpt5nsdcd39m7gon9p6h86letq2p8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgj0J4JuP1WbQQfk2N8RWjhvNgXRNQTMQ',
    appId: '1:871067145800:ios:148250e92bfac3e349ea7d',
    messagingSenderId: '871067145800',
    projectId: 'air-quality-8d73c',
    storageBucket: 'air-quality-8d73c.firebasestorage.app',
    iosClientId: '871067145800-g0rpt5nsdcd39m7gon9p6h86letq2p8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBf40h-KiRk2uyfwpMZx3hwT0z_n8rm-E',
    appId: '1:871067145800:web:595c71319b092b8e49ea7d',
    messagingSenderId: '871067145800',
    projectId: 'air-quality-8d73c',
    authDomain: 'air-quality-8d73c.firebaseapp.com',
    storageBucket: 'air-quality-8d73c.firebasestorage.app',
    measurementId: 'G-R1VCGVBKJ9',
  );
}
